"""uvodni schema registru

Revision ID: 30916da03a23
Revises: 
Create Date: 2026-08-28 20:45:53.089836
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identifikátory revize, používá je Alembic.
revision: str = '30916da03a23'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('oidc_subject', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='USER', nullable=False),
    sa.Column('role_source', sa.String(length=16), server_default='LOCAL', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('USER', 'ADMIN')", name=op.f('ck_users_role_allowed')),
    sa.CheckConstraint("role_source IN ('LOCAL', 'IDP')", name=op.f('ck_users_role_source_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_lower_email', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_users_oidc_subject', 'users', ['oidc_subject'], unique=True, postgresql_where=sa.text('oidc_subject IS NOT NULL'))
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decommissioned_by', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('deputy_user_id', sa.UUID(), nullable=True),
    sa.Column('tech_admin_user_id', sa.UUID(), nullable=False),
    sa.Column('ai_model', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(lifecycle_state = 'DECOMMISSIONED' AND decommissioned_at IS NOT NULL) OR (lifecycle_state <> 'DECOMMISSIONED' AND decommissioned_at IS NULL)", name=op.f('ck_applications_decommissioned_at_iff_decommissioned')),
    sa.CheckConstraint("classification IS NULL OR classification IN ('SMALL', 'MEDIUM', 'LARGE')", name=op.f('ck_applications_classification_allowed')),
    sa.CheckConstraint("lifecycle_state IN ('DRAFT', 'IN_DEVELOPMENT', 'TESTING', 'IN_PRODUCTION', 'DECOMMISSIONED')", name=op.f('ck_applications_lifecycle_state_allowed')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_applications_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decommissioned_by'], ['users.id'], name=op.f('fk_applications_decommissioned_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deputy_user_id'], ['users.id'], name=op.f('fk_applications_deputy_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_applications_owner_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tech_admin_user_id'], ['users.id'], name=op.f('fk_applications_tech_admin_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('ix_applications_active', 'applications', ['lifecycle_state'], unique=False, postgresql_where=sa.text("lifecycle_state <> 'DECOMMISSIONED'"))
    op.create_index('ix_applications_classification', 'applications', ['classification'], unique=False)
    op.create_index('ix_applications_decommissioned_at', 'applications', ['decommissioned_at'], unique=False)
    op.create_index('ix_applications_department', 'applications', ['department'], unique=False)
    op.create_index('ix_applications_deputy_user_id', 'applications', ['deputy_user_id'], unique=False)
    op.create_index('ix_applications_lifecycle_state', 'applications', ['lifecycle_state'], unique=False)
    op.create_index('ix_applications_lower_name', 'applications', [sa.literal_column('lower(name)')], unique=False)
    op.create_index('ix_applications_owner_user_id', 'applications', ['owner_user_id'], unique=False)
    op.create_index('ix_applications_tech_admin_user_id', 'applications', ['tech_admin_user_id'], unique=False)
    op.create_index('uq_applications_lower_name', 'applications', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.Text(), nullable=True),
    sa.Column('actor_display_name', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("action IN ('SIGN_IN', 'SIGN_OUT', 'APP_CREATED', 'APP_UPDATED', 'APP_DECOMMISSIONED', 'APP_REACTIVATED', 'CLASSIFICATION_SET', 'CLASSIFICATION_OVERRIDDEN', 'ROLE_CHANGED', 'ACCESS_DENIED')", name=op.f('ck_audit_log_action_allowed')),
    sa.CheckConstraint("entity_type IS NULL OR entity_type IN ('APPLICATION', 'USER', 'SESSION')", name=op.f('ck_audit_log_entity_type_allowed')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_actor_user_id', 'audit_log', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_occurred_at', 'audit_log', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('classification_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('previous_classification', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IN ('SMALL', 'MEDIUM', 'LARGE')", name=op.f('ck_classification_log_classification_allowed')),
    sa.CheckConstraint("previous_classification IS NULL OR previous_classification IN ('SMALL', 'MEDIUM', 'LARGE')", name=op.f('ck_classification_log_previous_classification_allowed')),
    sa.CheckConstraint("source <> 'ADMIN_OVERRIDE' OR (reason IS NOT NULL AND length(trim(reason)) > 0)", name=op.f('ck_classification_log_admin_override_requires_reason')),
    sa.CheckConstraint("source IN ('HUMAN', 'ADMIN_OVERRIDE')", name=op.f('ck_classification_log_source_allowed')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_classification_log_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_classification_log_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classification_log'))
    )
    op.create_index('ix_classification_log_application_created', 'classification_log', ['application_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classification_log_application_created', table_name='classification_log')
    op.drop_table('classification_log')
    op.drop_index('ix_audit_log_occurred_at', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_user_id', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_applications_lower_name', table_name='applications')
    op.drop_index('ix_applications_tech_admin_user_id', table_name='applications')
    op.drop_index('ix_applications_owner_user_id', table_name='applications')
    op.drop_index('ix_applications_lower_name', table_name='applications')
    op.drop_index('ix_applications_lifecycle_state', table_name='applications')
    op.drop_index('ix_applications_deputy_user_id', table_name='applications')
    op.drop_index('ix_applications_department', table_name='applications')
    op.drop_index('ix_applications_decommissioned_at', table_name='applications')
    op.drop_index('ix_applications_classification', table_name='applications')
    op.drop_index('ix_applications_active', table_name='applications', postgresql_where=sa.text("lifecycle_state <> 'DECOMMISSIONED'"))
    op.drop_table('applications')
    op.drop_index('uq_users_oidc_subject', table_name='users', postgresql_where=sa.text('oidc_subject IS NOT NULL'))
    op.drop_index('uq_users_lower_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
